import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Dell PowerEdge R750',
    slug: 'dell-poweredge-r750',
    sku: 'DELL-R750-001',
    category: 'Servers',
    brand: 'Dell',
    description: 'The Dell EMC PowerEdge R750 is a full-featured enterprise server, delivering outstanding performance for the most demanding workloads.',
    price: 375000,
    specs: { 'CPU': '2x Intel Xeon Gold', 'RAM': '64GB DDR4', 'Storage': 'No HDD (Bays Only)', 'Form Factor': '2U Rack' },
    stock: 10,
    imageUrl: 'https://picsum.photos/seed/server1/400/300',
    condition: 'New',
    isActive: true,
    isFeatured: true
  },
  {
    id: 'p2',
    name: 'HPE ProLiant DL380 Gen10',
    slug: 'hpe-proliant-dl380-gen10',
    sku: 'HPE-DL380-G10',
    category: 'Servers',
    brand: 'HP',
    description: 'Adaptable for diverse workloads and environments, the secure 2P 2U HPE ProLiant DL380 Gen10 Server delivers world-class performance.',
    price: 325000,
    specs: { 'CPU': 'Intel Xeon Silver', 'RAM': '32GB DDR4', 'Form Factor': '2U Rack', 'Controller': 'Smart Array P408i-a' },
    stock: 15,
    imageUrl: 'https://picsum.photos/seed/server2/400/300',
    condition: 'Refurbished',
    isActive: true,
    isFeatured: true
  },
  {
    id: 'p3',
    name: 'Lenovo ThinkPad X1 Carbon Gen 10',
    slug: 'lenovo-thinkpad-x1-carbon-gen-10',
    sku: 'LEN-X1-G10',
    category: 'Laptops',
    brand: 'Lenovo',
    description: 'Our flagship business laptop. Powered by 12th Gen Intel Core processors and running on Windows 11 Pro.',
    price: 158000,
    specs: { 'CPU': 'i7-1260P', 'RAM': '16GB', 'SSD': '512GB NVMe', 'Screen': '14" IPS' },
    stock: 50,
    imageUrl: 'https://picsum.photos/seed/laptop1/400/300',
    condition: 'New',
    isActive: true,
    isFeatured: true
  },
  {
    id: 'p4',
    name: 'MacBook Pro 16"',
    slug: 'macbook-pro-16',
    sku: 'APL-MBP-16',
    category: 'Laptops',
    brand: 'Apple',
    description: 'Supercharged by M2 Pro or M2 Max. The most powerful MacBook Pro ever.',
    price: 249000,
    specs: { 'CPU': 'M2 Pro', 'RAM': '16GB', 'SSD': '512GB', 'Screen': '16" Liquid Retina XDR' },
    stock: 25,
    imageUrl: 'https://picsum.photos/seed/laptop2/400/300',
    condition: 'New',
    isActive: true,
    isFeatured: false
  },
  {
    id: 'p5',
    name: 'Dell Precision 7920 Tower',
    slug: 'dell-precision-7920-tower',
    sku: 'DELL-PREC-7920',
    category: 'Workstations',
    brand: 'Dell',
    description: 'The world\'s most powerful workstation. Ready for AI and VR.',
    price: 285000,
    specs: { 'CPU': 'Xeon Gold 6200', 'GPU': 'NVIDIA RTX A4000', 'RAM': '128GB', 'OS': 'Windows 11 Pro' },
    stock: 5,
    imageUrl: 'https://picsum.photos/seed/workstation1/400/300',
    condition: 'Refurbished',
    isActive: true,
    isFeatured: true
  },
  {
    id: 'p6',
    name: 'IBM FlashSystem 5200',
    slug: 'ibm-flashsystem-5200',
    sku: 'IBM-FS-5200',
    category: 'Storage',
    brand: 'IBM',
    description: 'Designed to speed up enterprise apps and provide enterprise-grade features.',
    price: 850000,
    specs: { 'Type': 'NVMe Flash', 'Capacity': '38TB Raw', 'Controller': 'Dual Active', 'Connectivity': 'Fibre Channel' },
    stock: 2,
    imageUrl: 'https://picsum.photos/seed/storage1/400/300',
    condition: 'Refurbished',
    isActive: true,
    isFeatured: false
  },
  {
    id: 'p7',
    name: '32GB DDR4 ECC RAM Stick',
    slug: '32gb-ddr4-ecc-ram-stick',
    sku: 'OPT-RAM-32',
    category: 'Option & Spares',
    brand: 'HP',
    description: 'Certified HP SmartMemory for Gen10 servers.',
    price: 18500,
    specs: { 'Type': 'DDR4-2933', 'Capacity': '32GB', 'Rank': '2Rx4', 'Voltage': '1.2V' },
    stock: 100,
    imageUrl: 'https://picsum.photos/seed/ram/400/300',
    condition: 'New',
    isActive: true,
    isFeatured: false
  },
  {
    id: 'p8',
    name: 'Cisco UCS C220 M5',
    slug: 'cisco-ucs-c220-m5',
    sku: 'CISCO-C220-M5',
    category: 'Servers',
    brand: 'Cisco',
    description: 'The Cisco UCS C220 M5 Rack Server delivers record-breaking performance and efficiency for a wide range of workloads.',
    price: 295000,
    specs: { 'CPU': '2x Xeon Silver 4210', 'RAM': '32GB', 'Storage': '2x 480GB SSD', 'Form Factor': '1U Rack' },
    stock: 8,
    imageUrl: 'https://picsum.photos/seed/server3/400/300',
    condition: 'Refurbished',
    isActive: true,
    isFeatured: true
  }
];